/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d2229f53-f045-4591-9dd0-bc612bd648e9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ulCtmqYhD",
    "aws_user_pools_web_client_id": "4akf4f9qnkk45aoa77m887083c",
    "oauth": {}
};


export default awsmobile;
