/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d2229f53-f045-4591-9dd0-bc612bd648e9",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ulCtmqYhD",
    "aws_user_pools_web_client_id": "4akf4f9qnkk45aoa77m887083c",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://p4dhlemvn5frvnmgfk7327vxya.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zjluzfskr5hcfa6h7ndpuu77iy"
};


export default awsmobile;
